# Generated by Django 5.1.4 on 2025-01-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_valor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=150),
        ),
    ]
