# Generated by Django 5.1.4 on 2025-01-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_valor', '0003_alter_libro_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'permissions': [('development', 'Permiso como Desarrollador'), ('scrum_master', 'Permiso como Scrum Master'), ('product_owner', 'Permiso como Product Owner')]},
        ),
    ]
